<?php

/**
 * @file
 * Examples showing how to use some of the new JavaScript features in Drupal 7.
 */

/**
 * Implements hook_help().
 */
function js_offline_help($path, $arg) {

  if ($path == 'admin/help#js_offline') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Offline.js is a library to automatically alert your users when they have lost internet connectivity, like Gmail.
It captures AJAX requests which were made while the connection was down, and remakes them when it is back up, so your app reacts perfectly.
') . '</p>';
    return $output;
  }
}

/**
* Implementation of hook_menu().
*/
function js_offline_menu() {

  $items['admin/config/js-offline'] = array(
  'title' => t('Choose Theme JS Offline'),
  'description' => t('You can select theme js offline'),
  'page callback' => 'system_admin_menu_block_page',
  'access arguments' => array('administer site configuration'),
  'file' => 'system.admin.inc',
  'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/js-offline/settings'] = array(
  'title' => t('Choose Theme JS Offline'),
  'description' => t('You can select theme js offline'),
  'page callback' => 'drupal_get_form',
  'page arguments' => array('js_offline_admin_settings'),
  'access arguments' => array('administer site configuration'),
  'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function js_offline_list_theme_css(){

  $files = file_scan_directory(drupal_get_path('module', 'js_offline'). '/theme/css', '/.*\.css$/');

  foreach ($files as $absolute => $file) {
      $filesess[$file->name] = drupal_substr($file->name, 14, 14);
   }
   return $filesess;

}


function js_offline_admin_settings() {

  $form['js_offline_theme_show'] = array(
  '#type' => 'select',
  '#title' => t('Select Theme'),
  '#options' =>  js_offline_list_theme_css(),
  '#default_value' => variable_get('js_offline_theme_show', 'offline-theme-default'),
  '#description' => t('All the node types selected below will be shown'),
  );

  return system_settings_form($form);
}

function js_offline_preprocess_html(&$variables) {

  $name_css = variable_get('js_offline_theme_show');

  drupal_add_js(drupal_get_path('module', 'js_offline') . '/js/offline.min.js');
  drupal_add_css(drupal_get_path('module', 'js_offline') . '/theme/css/'. $name_css .'.css');
}

